#
# NODE_ENV=development
# NOTE: Set CONFIG_FILE to swap out this config file.
#

app:
  title: 'Kubenet Console'
  org': 'DXOS.org'
  theme: 'dark'
  website: 'https://dxos.org'
  publicUrl: '/console'

api:
  server: 'https://demo.kube.dxos.network'
  path: '/api'
  intervalLog: 5000
  pollInterval: 10000

system:
  debug: 'dxos:console:*'

services:
  app:
    prefix: '/app'
    server: 'https://demo.kube.dxos.network'

  wns:
    server: 'https://demo.kube.dxos.network/dxos/wns/api'
    webui: 'https://demo.kube.dxos.network/dxos/wns/console'

  signal:
    server: 'wss://demo.kube.dxos.network/dxos/signal'
    api: 'https://demo.kube.dxos.network/dxos/signal'

  ipfs:
    server: 'https://demo.kube.dxos.network/dxos/ipfs/api'
    gateway: 'https://demo.kube.dxos.network/dxos/ipfs/gateway'

  wellknown:
    endpoint: 'https://demo.kube.dxos.network/.well-known/dxos'
